---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    networks:
      - wgnet
      - proxy
    ports:
      - 9696:9696
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)'
      - 'traefik.http.routers.prowlarr.entryPoints=websecure'
      - 'traefik.http.routers.prowlarr.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prowlarr.middlewares=authelia@docker'

networks:
  proxy:
    external: true
  wgnet:
    external: true
