api:
  dashboard: true
  debug: false
  insecure: false

log:
  level: "DEBUG"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"

providers:
  docker:
    network: "proxy"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: "false"
  file:
    filename: "/dynamic.yml"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "mail@example.com"
      storage: "/letsencrypt/acme.json"
      caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
